config/routes.rb
PhoneBook::Application.routes.draw do

  devise_for :users
  resources :phone_numbers do
    collection {
      get   :download
      post  :import
      get   :upload
    }
  end

  root 'phone_numbers#index'

  

end

app/models/phone_number.rb
require 'csv'
class PhoneNumber < ActiveRecord::Base
  belongs_to :user

  validates :number,  :user_id, :name, presence: true
  validates :number, uniqueness: {scope: :user_id}

  validates :number,  format: {with: /\A[\+\*]?(\([\d]+\))?[\-\.\s\d]+\Z/i},
                      length: {maximum: 30}

  validates :name, length: {maximum: 255}

  default_scope { order(:number) }

  def self.export(user)
    # tab-separated
    csv_string = CSV.generate(force_quotes: true, col_sep: "\t") do |csv|
      # header row
      #csv << ["number", "name"]

      # data rows
      user.phone_numbers.pluck(:number, :name).each do |phone_number|
        csv << phone_number
      end
    end
    csv_string
  end

  def self.import(file, user)
    CSV.foreach(file.path, force_quotes: true, col_sep: "\t") do |row|
      puts row.inspect
      phone_number = user.phone_numbers.find_or_initialize_by_number(row[0])
      phone_number.name = row[1]
      phone_number.save!
    end
    return true
  rescue => e
    return false
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :phone_numbers

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout :has_layout?

  protected

  def has_layout?
    request.xhr? ? 'ajax' : 'application'
  end

  def paginate_params
    per_page = params[:per_page].to_i
    per_page = 3 if per_page < 1
    per_page = 100 if per_page >100
    page = params[:page].to_i
    page = nil if page == 0
    {:page => page, :per_page => per_page}
  end

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end

end

app/controllers/phone_numbers_controller.rb
require 'csv'
class PhoneNumbersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_phone_number, only: [:show, :edit, :update, :destroy]

  # GET /phone_numbers
  def index
    phone_numbers
    render partial: 'table' if request.xhr?
  end

  # GET /phone_numbers/1
  def show
  end

  # GET /phone_numbers/new
  def new
    @phone_number = PhoneNumber.new
  end

  # GET /phone_numbers/1/edit
  def edit
  end

  def download
    send_data PhoneNumber.export(current_user),
      :type => 'text/csv; charset=iso-8859-1; header=present',
      :disposition => "attachment; filename=phone-numbers#{Time.now.utc.strftime("%Y-%m-%d")}.csv"
  end

  def upload
  end

  def import
    if PhoneNumber.import(params[:file], current_user)
      flash.now[:notice] = 'Phone numbers was successfully imported.'
    else
      flash.now[:error] = 'Wrong format!'
    end
  end

  # POST /phone_numbers
  def create
    @phone_number = PhoneNumber.new(phone_number_params)
    @phone_number.user = current_user

    if @phone_number.save
      redirect_to @phone_number, notice: 'Phone number was successfully created.'
    else
      flash.now[:error] = @phone_number.errors.full_messages
      render action: 'new'
    end
  end

  # PATCH/PUT /phone_numbers/1
  def update
    if @phone_number.update(phone_number_params)
      redirect_to @phone_number, notice: 'Phone number was successfully updated.'
    else
      flash.now[:error] = @phone_number.errors.full_messages
      render action: 'edit'
    end
  end

  # DELETE /phone_numbers/1
  def destroy
    @phone_number.destroy
    flash[:notice] = "Phone number was successfully destroyed."
    if request.xhr?
      phone_numbers
      render partial: 'table'
    else
      redirect_to phone_numbers_url
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone_number
      @phone_number = PhoneNumber.find(params[:id])
      # TODO: use cancan gem
      not_found if @phone_number.user != current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phone_number_params
      params.require(:phone_number).permit(:number, :name)
    end

    def phone_numbers
      @phone_numbers = current_user.phone_numbers.paginate(paginate_params)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # See: https://github.com/mislav/will_paginate/wiki/Link-renderer
  # change the default link renderer for will_paginate
  def will_paginate(collection_or_options = nil, options = {})
    if collection_or_options.is_a? Hash
      options, collection_or_options = collection_or_options, nil
    end
    options.merge!(renderer: FoundationPaginationHelper::LinkRenderer) unless options[:renderer]
    options.merge!(next_label: '»') unless options[:next_label]
    options.merge!(previous_label: '«') unless options[:previous_label]
    super *[collection_or_options, options].compact
  end

end

app/helpers/phone_numbers_helper.rb
module PhoneNumbersHelper
end

app/views/layouts/_flash.html.erb
<div id='flash' class='flash'>
  <% flash.each do |type, messages| %>
    <% c = {notice: :success, error: :alert}[type] %>
    <% [messages].flatten.each do |message| %>
      <div class="message alert-box <%= c %>"><%= message %></div>
    <% end -%>
  <% end -%>
</div>

app/views/layouts/ajax.html.erb
<%= render 'layouts/flash' %>
<%= yield %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <!-- Uncomment to make IE8 render like IE7 -->
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "PhoneBook" %></title>

    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <nav class="top-bar">
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to "PhoneBook", root_path %></a></h1>
        </li>
      </ul>
      <% if current_user %>
        <div class="top-bar-section">
          <ul class="right">
            <li class="divider"></li>
            <li><%= link_to current_user.email, edit_user_registration_path %></li>
            <li class="divider"></li>
            <li><%= link_to t('layout.logout'), destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
      <% end %>
    </nav>

    <div class="row">
      <div class="small-8 columns"><%= yield %></div>
      <div class="small-4 columns">
        <h2 class="subheader">Here is the test:</h2>
        <ul>
          <li>
            Create a phonebook which allows to keep peoples names and phones.
            It has one page which allows to add, edit and remove via ajax.
            it also allows to download the phonebook as a text file
            (e.g. tab-separated) and also upload a new version.
          </li>
          <li>
            When it uploads a file, it updates the phonebook, creating, updating and
            deleting records as appropriate. In short it has to *sync*
            (not just replace) the web-added data with the uploaded file.
          </li>
          <li>
            You are not allowed to use rich Javascript packages, except jQuery for this test, but we encourage you to use newest, stable versions of whatever you will use to solve this problem.
          </li>
        </ul>
      </div>
    </div>


    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/phone_numbers/_form.html.erb
<%= form_for(@phone_number, remote: true, html: {'data-replace' => '#phone-numbers-container'}) do |f| %>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit nil, class: 'button' %>
  </div>
<% end %>

app/views/phone_numbers/_table.html.erb
<table>
  <thead>
    <tr>
      <th><%= t 'activerecord.attributes.phone_number.number' %></th>
      <th><%= t 'activerecord.attributes.phone_number.name' %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @phone_numbers.each do |phone_number| %>
      <tr>
        <td><%= phone_number.number %></td>
        <td><%= phone_number.name %></td>
        <td><%= link_to 'Show', phone_number_path(phone_number), remote: true, 'data-replace' => '#phone-numbers-container' %></td>
        <td><%= link_to 'Edit', edit_phone_number_path(phone_number), remote: true, 'data-replace' => '#phone-numbers-container' %></td>
        <td><%= link_to 'Destroy', phone_number, method: :delete, data: { confirm: 'Are you sure?' }, remote: true, 'data-replace' => '#phone-numbers-container' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @phone_numbers %>

app/views/phone_numbers/edit.html.erb
<h4>Editing phone_number</h4>

<%= render 'form' %>

<%= link_to 'Back', phone_numbers_path, remote: true, 'data-replace' => '#phone-numbers-container' %>

app/views/phone_numbers/import.js.erb
$('#flash').html("<%= escape_javascript render('layouts/flash') %>");

app/views/phone_numbers/index.html.erb
<h1>Phone book</h1>

<%= link_to 'New Phone number', new_phone_number_path, class: 'button', remote: true, 'data-replace' => '#phone-numbers-container' %>
<%= link_to 'Download book', download_phone_numbers_path, class: 'button' %>
<%= link_to 'Upload book', upload_phone_numbers_path, class: 'button', remote: true, 'data-replace' => '#phone-numbers-container' %>

<div id='phone-numbers-container'>
  <%= render 'table' %>
</div>

app/views/phone_numbers/new.html.erb
<h4>New phone_number</h4>

<%= render 'form' %>

<%= link_to 'Back', phone_numbers_path, class: 'secondary', remote: true, 'data-replace' => '#phone-numbers-container' %>

app/views/phone_numbers/show.html.erb
<p>
  <strong><%= t 'activerecord.attributes.phone_number.number' %>:</strong>
  <%= @phone_number.number %>
</p>

<p>
  <strong><%= t 'activerecord.attributes.phone_number.name' %>:</strong>
  <%= @phone_number.name %>
</p>

<p>
  <strong><%= t 'activerecord.attributes.phone_number.created_at' %>:</strong>
  <%= @phone_number.created_at %>
</p>

<p>
  <strong><%= t 'activerecord.attributes.phone_number.updated_at' %>:</strong>
  <%= @phone_number.updated_at %>
</p>

<%= link_to 'Edit', edit_phone_number_path(@phone_number), remote: true, 'data-replace' => '#phone-numbers-container' %> |
<%= link_to 'Back', phone_numbers_path, remote: true, 'data-replace' => '#phone-numbers-container' %>

app/views/phone_numbers/upload.html.erb
<h4>Upload phone book</h4>

<%= form_for :phone_number, url: import_phone_numbers_path(:js), method: :post, remote: true, html: {multipart: true} do |f| %>
  <%= file_field_tag :file, accept: 'text/csv' %>
  <%= f.submit 'Upload phone book', class: 'button' %>
<% end %>

<%= link_to 'Back', phone_numbers_path, remote: true, 'data-replace' => '#phone-numbers-container' %>